### ISSUE TITLE
OpenHardwareMonitor v.0.9.8450.38520 crashed on startup in autoboot on Windows 10 Pro x64 22H2 19045.4046

### ISSUE THREAD

**Issue by AlexFish2013** [HardwareMonitor/OpenHardwareMonitor#1] opened 2024-02-16 06:44 UTC
Info from stability log:
Описание
Неправильный путь приложения:	F:\ProgramData\openhm\OpenHardwareMonitor.exe
Сигнатура проблемы
Имя проблемного события:	CLR20r3
Сигнатура проблемы 01:	OpenHardwareMonitor.exe
Сигнатура проблемы 02:	0.9.8450.38520
Сигнатура проблемы 03:	63f27750
Сигнатура проблемы 04:	OpenHardwareMonitor
Сигнатура проблемы 05:	0.9.8450.38520
Сигнатура проблемы 06:	63f27750
Сигнатура проблемы 07:	d
Сигнатура проблемы 08:	1
Сигнатура проблемы 09:	System.NullReferenceException
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	1033
Дополнительные сведения 1:	65e6
Дополнительные сведения 2:	65e6f806c0a2d2ba5da282b26e7f208b
Дополнительные сведения 3:	4e3f
Дополнительные сведения 4:	4e3f64e00f9ee5e63f22b3d2f02b9624
Файлы, помогающие описать проблему
WERInternalMetadata.xml
[OpenHardwareMonitor.exe.4036.dmp](https://github.com/sergiye/openhardwaremonitor/files/14307425/OpenHardwareMonitor.exe.4036.dmp)

**Comment by sergiye** [comment] 2024-02-16 10:42
can you please try to reproduce this error with the latest version?
also please provide reports in English in the future, thank you

**Comment by AlexFish2013** [comment] 2024-02-16 11:56
Well, dude. )
This error when booting the OS, your application didn't start from autoload and crashed.
I upgraded to the latest release, I'm watching.
I also hope that the work will be normalised.

Description
Incorrect application path: F:\ProgramData\openhm\OpenHardwareMonitor.exe
Problem Signature
Problem event name: CLR20r3
Problem Signature 01: OpenHardwareMonitor.exe
Problem Signature 02: 0.9.8450.38520
Problem Signature 03: 63f27750
Problem Signature 04: OpenHardwareMonitor
Problem Signature 05: 0.9.8450.38520
Problem Signature 06: 63f27750
Problem Signature 07: d
Problem Signature 08: 1
Problem Signature 09: System.NullReferenceException
OS Version: 10.0.19045.2.0.0.0.256.48
Locale ID: 1033
Additional information 1: 65e6
Additional Information 2: 65e6f806c0a2d2ba5da282b26e7f208b
Additional information 3: 4e3f
Additional information 4: 4e3f64e00f9ee5e63f22b3d2f02b9624
Files to help describe the problem
WERInternalMetadata.xml

**Comment by AlexFish2013** [comment] 2024-02-23 05:19
Hi. dude, again!

I have currently cancelled my use of your program for an indefinite period of time.
Because it is installed in my autoloader and every morning, when I boot up my computer, all settings, screen location and window size are removed.
The fans are not spinning, they are set to 0 speed.
Program v.1.0.8806 is unstable and it is a torment to work with it every day.  :(((

I went back to using an old but stable program, which can be found here: https://openhardwaremonitor.org/. 
Perhaps when you get your version up to stable operation with daily use, I'll look towards your fork.
Good luck and thanks for the opportunity to test your fork!

**Comment by sergiye** [comment] 2024-02-23 21:05
closed as no longer relevant

**Closed as completed by sergiye** 2024-02-23 21:05 UTC
Labels: wontfix

**Comment by sergiye** [comment] 2024-03-30 11:33
the problem was in saving settings on app close.
fixed in 1.0.8855
